# Generated by Django 2.2.5 on 2019-09-27 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CropRegister',
            fields=[
                ('FarmerR', models.IntegerField(primary_key=True, serialize=False)),
                ('CropI', models.IntegerField()),
                ('CropN', models.CharField(max_length=30)),
                ('Area', models.FloatField()),
                ('Typesoil', models.CharField(max_length=30)),
                ('WaterS', models.CharField(max_length=30)),
                ('Sdate', models.DateField()),
                ('Edate', models.DateField()),
                ('Loanreq', models.CharField(max_length=30)),
                ('Ferreq', models.CharField(max_length=30)),
                ('Chec', models.CharField(max_length=30)),
            ],
        ),
    ]
