# Generated by Django 2.2.5 on 2019-09-27 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgroTech', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropregister',
            name='Chec',
            field=models.CharField(default='0', max_length=30),
        ),
    ]
