# Generated by Django 2.2.5 on 2019-09-28 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgroTech', '0002_auto_20190927_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=30)),
                ('Lname', models.CharField(max_length=30)),
                ('Bdate', models.DateField()),
                ('Uname', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=254)),
                ('Mobile', models.IntegerField()),
                ('Gender', models.CharField(max_length=30)),
                ('Address', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('pincode', models.IntegerField()),
                ('state', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('Tland', models.IntegerField()),
                ('Ctype', models.CharField(max_length=30)),
            ],
        ),
    ]
