# Generated by Django 2.2.5 on 2019-09-30 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgroTech', '0005_auto_20190930_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumerSign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=30)),
                ('Lname', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=30)),
                ('Gender', models.CharField(max_length=30)),
                ('Qualification', models.CharField(max_length=30)),
                ('Ddate', models.DateField(max_length=30)),
                ('IDproof', models.CharField(max_length=30)),
                ('Address', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=30)),
                ('Cpassword', models.CharField(max_length=30)),
            ],
        ),
    ]
