# Generated by Django 2.2.5 on 2019-10-10 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AgroTech', '0007_auto_20191010_1233'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AgentSign',
            new_name='AgentInfo',
        ),
        migrations.RenameModel(
            old_name='ConsumerSign',
            new_name='ConsumerInfo',
        ),
        migrations.RenameModel(
            old_name='Contactus',
            new_name='Contact_us',
        ),
    ]
