# Generated by Django 2.2.5 on 2019-10-10 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgroTech', '0008_auto_20191010_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductId', models.CharField(max_length=30)),
                ('ProductName', models.CharField(max_length=30)),
                ('ProductImage', models.FileField(upload_to='')),
                ('FarmerDetails', models.CharField(max_length=30)),
                ('Contact_info', models.CharField(max_length=30)),
                ('Price', models.FloatField()),
            ],
        ),
    ]
