# Generated by Django 2.2.5 on 2019-10-11 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AgroTech', '0009_add_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentinfo',
            name='Cpassword',
        ),
        migrations.RemoveField(
            model_name='agentinfo',
            name='Password',
        ),
        migrations.RemoveField(
            model_name='consumerinfo',
            name='Cpassword',
        ),
        migrations.RemoveField(
            model_name='consumerinfo',
            name='Password',
        ),
    ]
