# Generated by Django 2.2.5 on 2019-10-14 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgroTech', '0010_auto_20191011_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_items',
            name='ProductImage',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
