# Generated by Django 2.2.5 on 2019-10-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgroTech', '0012_auto_20191019_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Regnumber', models.IntegerField(default=None)),
                ('Fname', models.CharField(max_length=30)),
                ('Lname', models.CharField(max_length=30)),
                ('Bdate', models.DateField()),
                ('Uname', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=254)),
                ('Mobile', models.IntegerField()),
                ('Gender', models.CharField(max_length=30)),
                ('Address', models.CharField(max_length=30)),
                ('City', models.CharField(max_length=30)),
                ('Pincode', models.IntegerField()),
                ('State', models.CharField(max_length=30)),
                ('Country', models.CharField(max_length=30)),
                ('Tland', models.IntegerField()),
                ('upimage', models.FileField(upload_to='documents/')),
                ('Ctype', models.CharField(max_length=30)),
            ],
        ),
    ]
