# Generated by Django 2.2.5 on 2019-10-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgroTech', '0013_farmerregister'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FarmerR', models.IntegerField(default=None)),
                ('CropI', models.IntegerField()),
                ('CropN', models.CharField(max_length=30)),
                ('Area', models.FloatField()),
                ('Typesoil', models.CharField(max_length=30)),
                ('WaterS', models.CharField(max_length=30)),
                ('Sdate', models.DateField(auto_now_add=True)),
                ('Edate', models.DateField()),
                ('Loanreq', models.CharField(max_length=30)),
                ('Ferreq', models.CharField(max_length=30)),
                ('Chec', models.CharField(default='0', max_length=30)),
            ],
        ),
    ]
