# Generated by Django 2.2.5 on 2019-10-27 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgroTech', '0014_cropregister'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerregister',
            name='id',
        ),
        migrations.AlterField(
            model_name='add_items',
            name='ProductId',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='farmerregister',
            name='Regnumber',
            field=models.IntegerField(default=None, primary_key=True, serialize=False),
        ),
    ]
