# Generated by Django 2.2.5 on 2019-10-27 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AgroTech', '0015_auto_20191027_1156'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SendFeed',
        ),
    ]
