# Generated by Django 2.2.5 on 2019-11-01 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgroTech', '0016_delete_sendfeed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumerinfo',
            name='Qualification',
            field=models.IntegerField(),
        ),
    ]
