# Generated by Django 2.2.5 on 2019-11-11 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgroTech', '0017_auto_20191101_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_items',
            name='Quantity',
            field=models.IntegerField(default=None),
        ),
    ]
