# Generated by Django 2.2.5 on 2019-11-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgroTech', '0021_auto_20191111_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='ProductName',
            field=models.CharField(default='0', max_length=30),
        ),
    ]
