# Generated by Django 2.2.5 on 2019-11-16 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AgroTech', '0022_checkout_productname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropregister',
            name='FarmerR',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='AgroTech.FarmerRegister'),
        ),
    ]
