# Generated by Django 2.2.5 on 2019-11-16 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AgroTech', '0023_auto_20191116_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropregister',
            name='FarmerR',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AgroTech.FarmerRegister'),
        ),
    ]
