# Generated by Django 2.2.5 on 2019-11-16 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AgroTech', '0024_auto_20191116_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerregister',
            name='Uname',
        ),
    ]
