# Generated by Django 2.2.5 on 2019-11-20 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AgroTech', '0025_remove_farmerregister_uname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cropregister',
            old_name='FarmerR',
            new_name='farmerRegister',
        ),
    ]
