# Generated by Django 2.2.5 on 2019-11-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgroTech', '0026_auto_20191120_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(default='0', max_length=30)),
                ('Email', models.EmailField(max_length=254)),
                ('Address', models.CharField(max_length=30)),
            ],
        ),
    ]
