# Generated by Django 2.2.5 on 2019-11-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgroTech', '0027_cartuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='id',
        ),
        migrations.AlterField(
            model_name='checkout',
            name='ProductId',
            field=models.IntegerField(default=None, primary_key=True, serialize=False),
        ),
    ]
