# Generated by Django 2.2.5 on 2019-11-23 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgroTech', '0028_auto_20191123_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seconddata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Today', models.CharField(max_length=30)),
                ('Head', models.CharField(max_length=30)),
                ('img', models.CharField(max_length=30)),
                ('quote', models.CharField(max_length=30)),
                ('subquote', models.CharField(max_length=30)),
            ],
        ),
    ]
