# Generated by Django 2.2.5 on 2019-12-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgroTech', '0030_auto_20191123_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='user',
            field=models.CharField(default='0', max_length=30),
        ),
    ]
